on: [push]

jobs:
  compile-typescript:
    runs-on: ubuntu-latest
    name: compile all typescript files into one javascript file
    steps:
    - uses: actions/checkout@v1
    
    - name: "npm ci"
      run: npm ci

    - name: "npm run dist"
      run: npm run dist
      
    - name: "push compiled file"
      uses: alexesprit/action-update-file@v0.1.0
      with:
        file-path: dist/index.js
        commit-msg: Compile all ts into one file
        github-token: ${{ secrets.GITHUB_TOKEN }}
