on: [push]

jobs:
  compile-typescript:
    runs-on: ubuntu-latest
    name: compile all typescript files into one javascript file
    steps:
    - uses: actions/checkout@v1
    
    - name: "npm ci"
      run: npm ci

    - name: "npm run dist"
      run: npm run dist
