on:
  push:
    branches: 
      - master

jobs:
  compile-typescript:
    runs-on: ubuntu-latest
    name: compile all typescript files into one javascript file
    steps:
    - uses: actions/checkout@v1
    
    - name: "npm ci"
      run: npm ci

    - name: "npm run dist"
      run: npm run dist
      
    - name: "push compiled file"
      uses: alexesprit/action-update-file@v0.1.0
      with:
        file-path: dist/index.js
        commit-msg: Compile all ts into one file
        github-token: ${{ secrets.GITHUB_TOKEN }}

  test-action:
    runs-on: ubuntu-latest
    needs: [compile-typescript]
    steps:
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
